### ISSUE TITLE
It's killing me!

### ISSUE THREAD

**Issue by tsiq-swyx** [pomber/hitchcock#1]
what is it!!

**Comment by pomber** [comment]
"There is no terror in the bang, only in the anticipation of it." 😛 
I'll try to push it this weekend

**Comment by tsiq-swyx** [comment]
ok :) was hoping to include you in a Suspense presentation im giving on
wednesday

**Comment by pomber** [comment]
Still very experimental but here is a demo: https://codesandbox.io/s/kk2v1op3m5

**Comment by tsiq-swyx** [comment]
THIS IS AMAZING. WOW!!!

**Comment by tsiq-swyx** [comment]
any idea what happens when promises get rejected? they seem to be saying on twitter that componentDidCatch should be able to catch the rejected promise, but my experiments don't seem to be bearing this out.

**Comment by pomber** [comment]
Are you talking about hitchcock or react suspense in general?  

For hitchcock it's not implemented yet.

For the rest of the cases, I think it depends on the cache you are using if you are using any. Apparently, the cache should handle the promise rejection, store the error and throw it the next time you try to read that key. 

[Here](https://github.com/facebook/react/blob/master/packages/simple-cache-provider/src/SimpleCacheProvider.js#L197) is how simple-cache-provider does it.

**Comment by tsiq-swyx** [comment]
i think this applies to both.

so just to be clear we're on the same page, i add a throw (or a reject) in your API:
![image](https://user-images.githubusercontent.com/35976578/38326781-af87e0b6-3814-11e8-887b-0c1f56505751.png)

and then i wrap with an Error Boundary:

![image](https://user-images.githubusercontent.com/35976578/38326946-0c130a9a-3815-11e8-903a-96758e07ec1e.png)


I understand that you havent implemented the reject caching in your cache, but i tried this error boundary catching with simple cache provider yesterday and it didnt work at all. just says unhandled rejection. im wondering if they havent shipped error boundaries that can handle this yet.

**Comment by pomber** [comment]
I just tested it with simple-cache-provider and got the same result as you, the error boundary didn't catch it. I've read that react 16.3 included a rewrite of error boundaries, maybe the alpha version we are using doesn't have that code merged.

**Comment by tsiq-swyx** [comment]
ah ok so at least im not fundamentally misunderstanding something. thanks very much! keeping a close watch on this one. i def think the debugger belongs in react devtools eventually

**Comment by pomber** [comment]
@tsiq-swyx looks like handling rejections was missing: https://github.com/facebook/react/pull/12279/commits/75048c2935a4443d93bbdb6d074447d1f8aca761

**Comment by tsiq-swyx** [comment]
awesome! I dont know how you find this stuff. but thanks a lot for sharing
it!
